version: 2

sphinx:
  configuration: docs/source/conf.py

formats: all

build:
  image: latest

python:
  version: 3.10
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .
