version: 2

sphinx:
  configuration: docs/source/conf.py

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .
